# Site settings
title: 瀚阳的博客
header-img: img/mc-title.jpg
email: lauhonyeung@gmail.com
description: "关于VR、游戏、编程、技术"
baseurl: "/blogcn"
redirect: "/blogcn"
url: "/blogcn"
twitter_username: FonzieLiu
github_username:  fonzieyang
facebook_page:  lauhonyeung
weibo_username: lauhonyeung
linkedin_username: lauhonyeung
zhihu_username: liu-han-yang

# Build settings
markdown: kramdown
highlighter: rouge
#pygments
permalink: /:title
gems: [jekyll-paginate]
#gem 'jekyll-paginate', group: :jekyll_plugins
paginate_path: "page:num"
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]

